name: web-advanced-frond-end CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: 步骤：第一步 -> 设置环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 步骤：第二步 -> 安装依赖
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: 步骤：第三步 -> 部署脚本
        env:
          ACCESS_TOKEN_DEPLOY: ${{secrets.ACTIONS_ACCESS_TOKEN_WEB_CI }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/.vitepress/dist
          CNAME: web.veaba.me
        run: |
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh
